/**
 * The transform package is used for transforming a textual input to a textual output.
 * Common use is to transform an XML input to a XML or JSON output, e.g. to deliver JSON-LD from a MODS source.
 *
 * The transform package uses a ServiceLoader to discover and control transformers:
 * New transformers are added by creating a {@link dk.kb.present.transform.DSTransformer} with a corresponding
 * {@link dk.kb.present.transform.DSTransformerFactory} and registering the factory in the file
 * {@code src/main/resources/META-INF/services/dk.kb.present.transform.DSTransformerFactory}.
 *
 * Transformer instances are created by {@link dk.kb.present.transform.TransformerController}.
 *
 * Overview of mapping between fields from preservica.
 * The XSLT Transformers created by the {@link dk.kb.present.transform.XSLTFactory} using XSLTs related to preservica
 * metadata are connected in the following way:
 * <table>
 * 	<caption>Mapping between preservica fields</caption>
 * 	<thead>
 * 	<tr>
 * 		<th>Preservica OAI-PMH XML</th>
 * 		<th>SolrDoc</th>
 * 		<th>Schema.org JSON</th>
 * 		<th>Comment</th>
 * 	</tr>
 * 	</thead>
 * 	<tbody>
 * 	<tr>
 * 		<td></td>
 * 		<td>id</td>
 * 		<td></td>
 * 		<td>This ID is created from the name of the record in the preservica OAI-PMH harvest.</td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>origin</td>
 * 		<td></td>
 * 		<td>Origin is not present in preservica. It is created from where the metadata originates from. In this case,
 * 	        the Radio/TV collection.</td>
 * 	</tr>
 * 	<tr>
 * 		<td>pbcoreGenre/genre</td>
 * 		<td>categories</td>
 * 		<td></td>
 * 		<td>All types of genres from preservica are present here.</td>
 * 	</tr>
 * 	<tr>
 * 		<td>pbcoreInstantiation/formatLocation</td>
 * 		<td>collection</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td>pbcoreGenre/genre</td>
 * 		<td>genre</td>
 * 		<td></td>
 * 		<td>Extracted from the field which contains 'hovedgenre:'</td>
 * 	</tr>
 * 	<tr>
 * 		<td>pbcoreInstantiation/formatMediaType</td>
 * 		<td>resource_description</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td>pbcoreTitle/title</td>
 * 		<td>title</td>
 * 		<td></td>
 * 		<td>Is extracted when pbcoreTitle/titleType = 'titel'</td>
 * 	</tr>
 * 	<tr>
 * 		<td>pbcoreTitle/title</td>
 * 		<td>original_title</td>
 * 		<td></td>
 * 		<td>Is extracted when pbcoreTitle/titleType = 'originaltitel'</td>
 * 	</tr>
 * 	<tr>
 * 		<td>pbcorePublisher/publisherRole</td>
 * 		<td>creator_affiliation</td>
 * 		<td></td>
 * 		<td>The solr field has the same name across collections.</td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>notes</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>resource_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td>pbcoreTitle/title</td>
 * 		<td>episode_title</td>
 * 		<td></td>
 * 		<td>Is extracted when pbcoreTitle/titleType = 'episodetitel'</td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>ritzau_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>tvmeter_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>duration_ms</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>color</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>video_quality</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>surround_sound</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>premiere</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>aspect_ratio</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>manifestation_type</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>episode</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>number_of_episodes</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>live_broadcast</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>retransmission</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>abstract</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>description</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>genre_sub</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>has_subtitles</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>has_subtitles_for_hearing_impaired</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>pid</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_accession_ref</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_format_identifier_ritzau</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_format_identifier_nielsen</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_maingenre_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_channel_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_country_of_origin_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_ritzau_program_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_subgenre_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_episode_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_season_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_series_id</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_program_ophold</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_is_teletext</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_showviewcode</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_padding_seconds</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_access_individual_prohibition</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_access_claused</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_access_malfunction</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_access_comments</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_program_structure_missing_seconds_start</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_program_structure_missing_seconds_end</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_program_structure_holes</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tr>
 * 		<td></td>
 * 		<td>internal_program_structure_holes</td>
 * 		<td></td>
 * 		<td></td>
 * 	</tr>
 * 	<tbody>
 * </table>
 */
package dk.kb.present.transform;