openapi: 3.0.2
info:
  version: 'v1'
  title: '${project.name}'
  description: |
    Metadata delivery for the Royal Danish Library
  contact:
    email: '${user.name}@kb.dk'
  license:
    name: '${license.name}'
    url: '${license.url}'
servers:
  #  /api must match servlet-mapping in web.xml
  - url: '/${project.artifactId}/v1'
    description: 'Version 1'

paths:
  /ping:
    get:
      tags:
        - '${project.name}'
      summary: 'Ping the server to check if the server is reachable.'
      operationId: ping
      x-useGenericResponse: false # If enabled the method will return Response
      x-streamingOutput: false # If enabled the method will return StreamingOutput.
      responses:
        '200':
          description: 'OK'
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: 'Internal Error'
          content:
            text/plain:
              schema:
                type: string

  # This definition uses path: http://example.com/api/article/article-123A-v2
  /record/{id}:
    get:
      tags:
        - '${project.name}'
      summary: 'Retrieve metadata for the record with the given ID'
      operationId: getRecord
      # We assume a very large response here: Too large for showing directly in the Swagger UI.
      # The Content-Disposition for "x-streamingOutput: true" is set to disable inline display in Swagger UI, but
      # keep inline display when the link is pasted directly in a browser. Inspect the generated code for tweaks.
      parameters:
        - name: id
          in: path
          description: 'The ID of the record'
          required: true
          schema:
            type: string
            # Note: Constraints are not enforced by Swagger. They are only used as a contract
            minLength: 1
            example: 'images-dsfl_image-1234'
        - name: format
          in: query
          description: |
            The delivery format for the record:
            * JSON-LD: [Linked Data in JSON](https://json-ld.org/)
            * MODS: [Metadata Object Description Schema[(http://www.loc.gov/standards/mods/)
            * SolrXML: [Solr XML Formatted Index Updates)(https://solr.apache.org/guide/8_8/uploading-data-with-index-handlers.html#xml-formatted-index-updates)
            * raw: Metadata unchanged from the source.
          schema:
            type: string
            enum:  ['JSON-LD', 'MODS', 'SolrXML', "raw"]
            example: 'JSON-LD'
            default: 'JSON-LD'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                description: 'Format-specific representation of the record in JSON or JSON-LD'
                type: string
                format: binary
            application/xml:
              schema:
                description: 'Format-specific representation of the record in XML'
                type: string
                format: binary
        '404':
          description: 'Record ID is unknown'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
